import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import ParallaxWrapper from "./ParallaxWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <div>
        <ParallaxWrapper>
          <Navbar />
          {children}
          <Footer />
        </ParallaxWrapper>
        </div>
      </body>
    </html>
  );
}