'use client'
import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { ParallaxProvider } from "react-scroll-parallax";


export const meta: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <ParallaxProvider scrollAxis="horizontal">
        <Navbar/>
        {children}
        {/* <Footer/> */}
        </ParallaxProvider>
      </body>
    </html>
  );
}
